name: webusb_ws2812_build

on:
  push:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Environment Variables
      run: |
        echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
        echo "HOME = $HOME"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: list
      run: ls

    - name: install dependencies
      run: sudo apt-get install -y openjdk-8-jre bzip2 wget
      
    - name: download arm toolchain
      run: |
        cd $GITHUB_WORKSPACE
        cd ..
        wget -qO- https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 | tar -xj
        export PATH=$PATH:$(pwd)/gcc-arm-none-eabi-10-2020-q4-major/bin
        echo "PATH = $PATH"
        ls
                
