name: webusb_ws2812_build

on:
  push:
    branches: [ main ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Environment Variables
      run: |
        echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
        echo "GITHUB_PATH = $GITHUB_PATH"
        echo "HOME = $HOME"

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: list
      run: ls

    - name: install dependencies
      run: sudo apt-get install -y openjdk-8-jre bzip2 wget
      
    - name: download arm toolchain
      run: |
        cd $HOME
        wget -qO- https://developer.arm.com/-/media/Files/downloads/gnu-rm/10-2020q4/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 | tar -xj
        echo "$(pwd)/gcc-arm-none-eabi-10-2020-q4-major/bin" >> $GITHUB_PATH
        echo "PATH = $PATH"
        echo "GITHUB_PATH = $GITHUB_PATH"

    - name: download eclipse
      run: |
        cd $HOME
        wget -c https://ftp.jaist.ac.jp/pub/eclipse/technology/epp/downloads/release/2020-12/R/eclipse-embedcpp-2020-12-R-linux-gtk-x86_64.tar.gz -O - |  tar -xz -C .
        ls
        export PATH=$PATH:$(pwd)/eclipse
        echo "PATH = $PATH"
        echo "GITHUB_PATH = $GITHUB_PATH"
        
    - name: build
      run: |
        echo "PATH = $PATH"
        cd $GITHUB_WORKSPACE
        eclipse -nosplash -application org.eclipse.cdt.managedbuilder.core.headlessbuild -import $GITHUB_WORKSPACE -build webusb_ws2812/Debug -cleanBuild all
